# this yaml config for setup Ubuntu netplan(lan and wifi connect)
# using ethernet eth0 as direct connection need to set your laptop Ethernet connect to static as 192.168.10.xxx/24
# wifi is the main connection with internet
network:
    version: 2
    ethernets:
      eth0:
        addresses:
          - 192.168.10.222/24 # you can set any ip if you know what you are doing
        gateway4: 192.168.1.1
        nameservers:
          addresses: [8.8.8.8,8.8.4.4]
    wifis:
      wlan0:
        addresses:
          - 192.168.1.200/24 # you can set any ip same as your wifi network
        gateway4: 192.168.1.1
        nameservers:
          addresses: [192.168.1.234,192.168.1.245,8.8.8.8]
        access-points:
          "YOUR SSID":
             password: "YOUR PASSWORD"
 